#!/bin/bash
# This script helps ensure that microcomputers such as the ODROID XU4
# can connect to a Wi-Fi network without the GUI-based manager. On the
# ODROID XU4 and other microcomputers, there is a tendency for the Wi-Fi
# interface to be on a random interface wlan[0-5]. This script should 
# be called on startup by adding a call to it in  /etc/rc.local

log=/home/$USER/start_wifi_sh.log
# find the interfaces
ethif=`sudo iwlist scan 2>&1 | grep eth | awk -F" " {'print $1'}`
wlanif=`sudo iwlist scan 2>&1 | grep wlan | awk -F" " {'print $1'}`

#set the output file for the network configuration
if_file=/etc/network/interfaces

# set a wild guess if no wifi usb was present 
if [ -z $wlanif ]; then
   wlanif="wlan0"
fi

# build /etc/network/interfaces file
echo "# This file is autogenerated by /home/$USER/start_wifi.sh

# start_wifi.sh does its best to find the correct ethX and wlanX 
auto lo
iface lo inet loopback
manual $ethif
iface $ethif inet dhcp

allow-hotplug $wlanif
iface $wlanif inet dhcp
   wpa-ssid [PUT SSID HERE]
   wpa-psk [PUT PSK HERE]" > $if_file 

#bring wifi interface down
echo "-----------------------------------------"
echo "---- Putting interface [$wlanif] down -----"
echo "-----------------------------------------"
sudo ifdown "$wlanif"
sleep 1.0

#bring wifi interface up
echo "---------------------------------------"
echo "---- Putting interface [$wlanif] up -----" 
echo "---------------------------------------" 
sudo ifup "$wlanif"
echo "---------------------------------------" 
echo "- Hopefully WiFi is working now -------" 
echo "---------------------------------------" 
ifconfig | grep -A10 "$wlanif" | grep "inet addr" | awk -F" " {'print $2'}   

#configure the US settings for standard Wi-Fi frequency bands
sudo iw reg set US

sleep 10.0

